In [ ]:
#1. Python Data Analyst Project — E-Commerce Sales Analysis

In [62]:
#2.import numpy as np
import pandas as pd

# Reproducible random data
np.random.seed(42)

# Number of records
n = 5000

# Create product and category mapping
product_category = {
    "Laptop": "Electronics",
    "Mobile": "Electronics",
    "Tablet": "Electronics",
    "Headphones": "Accessories",
    "Keyboard": "Accessories",
    "Mouse": "Accessories",
    "Monitor": "Electronics",
    "Smartwatch": "Wearables"
}

# Generate products
products = np.random.choice(
    list(product_category.keys()),
    size=n
)

# Generate DataFrame
df = pd.DataFrame({
    "Order_ID": np.arange(10001, 10001 + n),

    "Customer_ID": np.random.randint(
        1001, 2001, n
    ),

    "Product": products,

    "Category": [
        product_category[p]
        for p in products
    ],

    "City": np.random.choice([
        "Delhi",
        "Mumbai",
        "Bangalore",
        "Chennai",
        "Kolkata",
        "Hyderabad",
        "Pune",
        "Patna"
    ], n),

    "Quantity": np.random.randint(
        1, 6, n
    ),

    "Price": np.random.randint(
        500, 100000, n
    ),

    "Discount": np.random.choice(
        [0, 5, 10, 15, 20],
        n
    ),

    "Payment_Method": np.random.choice([
        "UPI",
        "Credit Card",
        "Debit Card",
        "Cash",
        "Net Banking"
    ], n),

    "Order_Status": np.random.choice([
        "Delivered",
        "Delivered",
        "Delivered",
        "Delivered",
        "Cancelled",
        "Returned"
    ], n),

    "Rating": np.random.randint(
        1, 6, n
    ),

    "Order_Date": pd.to_datetime(
        np.random.choice(
            pd.date_range(
                "2025-01-01",
                "2025-12-31"
            ),
            size=n
        )
    )
})

# Display first 5 rows
df.head()

,Order_ID,Customer_ID,Product,Category,City,Quantity,Price,Discount,Payment_Method,Order_Status,Rating,Order_Date
0,10001,1947,Monitor,Electronics,Chennai,4,33146,15,Cash,Delivered,1,2025-02-12
1,10002,1687,Headphones,Accessories,Kolkata,3,93338,5,Cash,Delivered,3,2025-01-19
2,10003,1751,Keyboard,Accessories,Chennai,3,76626,0,Debit Card,Delivered,4,2025-01-16
3,10004,1772,Monitor,Electronics,Mumbai,2,40930,10,UPI,Delivered,2,2025-04-15
4,10005,1903,Tablet,Electronics,Kolkata,2,69159,15,Credit Card,Delivered,5,2025-10-06

In [63]:
#3. Understand the Dataset
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5000
Columns: 12

In [64]:
df.head()

,Order_ID,Customer_ID,Product,Category,City,Quantity,Price,Discount,Payment_Method,Order_Status,Rating,Order_Date
0,10001,1947,Monitor,Electronics,Chennai,4,33146,15,Cash,Delivered,1,2025-02-12
1,10002,1687,Headphones,Accessories,Kolkata,3,93338,5,Cash,Delivered,3,2025-01-19
2,10003,1751,Keyboard,Accessories,Chennai,3,76626,0,Debit Card,Delivered,4,2025-01-16
3,10004,1772,Monitor,Electronics,Mumbai,2,40930,10,UPI,Delivered,2,2025-04-15
4,10005,1903,Tablet,Electronics,Kolkata,2,69159,15,Credit Card,Delivered,5,2025-10-06

In [65]:
df.tail()

,Order_ID,Customer_ID,Product,Category,City,Quantity,Price,Discount,Payment_Method,Order_Status,Rating,Order_Date
4995,14996,1841,Keyboard,Accessories,Chennai,4,20643,10,Credit Card,Delivered,3,2025-05-07
4996,14997,1002,Mouse,Accessories,Delhi,3,76328,20,Net Banking,Cancelled,4,2025-02-08
4997,14998,1520,Tablet,Electronics,Hyderabad,4,62973,15,Debit Card,Delivered,1,2025-12-19
4998,14999,1762,Mobile,Electronics,Chennai,2,16517,20,UPI,Returned,5,2025-03-18
4999,15000,1651,Headphones,Accessories,Hyderabad,2,63702,20,Cash,Cancelled,2,2025-01-05

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        5000 non-null   int32
 1   Customer_ID     5000 non-null   int32
 2   Product         5000 non-null   str
 3   Category        5000 non-null   str
 4   City            5000 non-null   str
 5   Quantity        5000 non-null   int32
 6   Price           5000 non-null   int32
 7   Discount        5000 non-null   int32
 8   Payment_Method  5000 non-null   str
 9   Order_Status    5000 non-null   str
 10  Rating          5000 non-null   int32
 11  Order_Date      5000 non-null   datetime64[us]
dtypes: datetime64[us](1), int32(6), str(5)
memory usage: 254.0 KB

In [67]:
df.describe()

,Order_ID,Customer_ID,Quantity,Price,Discount,Rating,Order_Date
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000
mean,12500.500000,1501.847200,3.033000,50030.681400,9.914000,3.005200,2025-06-30 17:25:43.680000
min,10001.000000,1001.000000,1.000000,518.000000,0.000000,1.000000,2025-01-01 00:00:00
25%,11250.750000,1248.000000,2.000000,24506.000000,5.000000,2.000000,2025-04-01 00:00:00
50%,12500.500000,1503.000000,3.000000,49804.000000,10.000000,3.000000,2025-07-03 12:00:00
75%,13750.250000,1753.000000,4.000000,75425.500000,15.000000,4.000000,2025-09-27 00:00:00
max,15000.000000,2000.000000,5.000000,99980.000000,20.000000,5.000000,2025-12-31 00:00:00
std,1443.520003,288.858681,1.417432,28942.333639,7.078321,1.419851,NaN

In [68]:
#Columns:
df.columns

Index(['Order_ID', 'Customer_ID', 'Product', 'Category', 'City', 'Quantity',
       'Price', 'Discount', 'Payment_Method', 'Order_Status', 'Rating',
       'Order_Date'],
      dtype='str')

In [69]:
#4. Check Missing Values
df.isnull().sum()

Order_ID          0
Customer_ID       0
Product           0
Category          0
City              0
Quantity          0
Price             0
Discount          0
Payment_Method    0
Order_Status      0
Rating            0
Order_Date        0
dtype: int64

In [70]:
#Percentage:
missing_percentage = (
    df.isnull().sum() / len(df)
) * 100

print(missing_percentage)

Order_ID          0.0
Customer_ID       0.0
Product           0.0
Category          0.0
City              0.0
Quantity          0.0
Price             0.0
Discount          0.0
Payment_Method    0.0
Order_Status      0.0
Rating            0.0
Order_Date        0.0
dtype: float64

In [71]:
#5. Check Duplicate Data
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [72]:
#Remove duplicates:
df = df.drop_duplicates()

In [73]:
#6. Create Sales Column
df["Gross_Sales"] = (
    df["Quantity"] * df["Price"]
)

df.head()

,Order_ID,Customer_ID,Product,Category,City,Quantity,Price,Discount,Payment_Method,Order_Status,Rating,Order_Date,Gross_Sales
0,10001,1947,Monitor,Electronics,Chennai,4,33146,15,Cash,Delivered,1,2025-02-12,132584
1,10002,1687,Headphones,Accessories,Kolkata,3,93338,5,Cash,Delivered,3,2025-01-19,280014
2,10003,1751,Keyboard,Accessories,Chennai,3,76626,0,Debit Card,Delivered,4,2025-01-16,229878
3,10004,1772,Monitor,Electronics,Mumbai,2,40930,10,UPI,Delivered,2,2025-04-15,81860
4,10005,1903,Tablet,Electronics,Kolkata,2,69159,15,Credit Card,Delivered,5,2025-10-06,138318

In [77]:
#7. NumPy Analysis
total_sales = np.sum(df["Net_Sales"])

print("Total Sales:", total_sales)

Total Sales: 678898722.15

In [78]:
#Average Sales
average_sales = np.mean(df["Net_Sales"])

print("Average Sales:", average_sales)

Average Sales: 135779.74443

In [79]:
#Highest Sale
highest_sale = np.max(df["Net_Sales"])

print("Highest Sale:", highest_sale)

Highest Sale: 497455.0

In [80]:
#Lowest Sale
lowest_sale = np.min(df["Net_Sales"])

print("Lowest Sale:", lowest_sale)

Lowest Sale: 440.3

In [81]:
#Median
median_sales = np.median(df["Net_Sales"])

print("Median Sales:", median_sales)

Median Sales: 106760.4

In [82]:
#Standard Deviation
std_sales = np.std(df["Net_Sales"])

print("Standard Deviation:", std_sales)

Standard Deviation: 107728.54860976186

In [83]:
#8. Highest Sales Order
index = np.argmax(df["Net_Sales"])

df.iloc[index]

Order_ID                         13938
Customer_ID                       1885
Product                         Tablet
Category                   Electronics
City                           Chennai
Quantity                             5
Price                            99491
Discount                             0
Payment_Method             Net Banking
Order_Status                 Delivered
Rating                               5
Order_Date         2025-10-06 00:00:00
Gross_Sales                     497455
Discount_Amount                    0.0
Net_Sales                     497455.0
Name: 3937, dtype: object

In [84]:
#Lowest:
index = np.argmin(df["Net_Sales"])

df.iloc[index]

Order_ID                         14439
Customer_ID                       1494
Product                          Mouse
Category                   Accessories
City                           Chennai
Quantity                             1
Price                              518
Discount                            15
Payment_Method                     UPI
Order_Status                 Delivered
Rating                               2
Order_Date         2025-03-28 00:00:00
Gross_Sales                        518
Discount_Amount                   77.7
Net_Sales                        440.3
Name: 4438, dtype: object

In [85]:
#9. Product Analysis
product_sales = (
    df.groupby("Product")["Net_Sales"]
    .sum()
    .sort_values(ascending=False)
)

product_sales

Product
Headphones    95077210.70
Keyboard      89953111.65
Mobile        86256166.80
Mouse         85391177.80
Laptop        83952428.85
Tablet        82988851.75
Smartwatch    80475988.55
Monitor       74803786.05
Name: Net_Sales, dtype: float64

In [86]:
#Top 5 Products
product_sales.head(5)

Product
Headphones    95077210.70
Keyboard      89953111.65
Mobile        86256166.80
Mouse         85391177.80
Laptop        83952428.85
Name: Net_Sales, dtype: float64

In [87]:
#Product Quantity
product_quantity = (
    df.groupby("Product")["Quantity"]
    .sum()
    .sort_values(ascending=False)
)

product_quantity

Product
Headphones    2062
Keyboard      2014
Laptop        1969
Mobile        1900
Mouse         1870
Tablet        1859
Smartwatch    1756
Monitor       1735
Name: Quantity, dtype: int32

In [88]:
#10. Category Analysis
category_analysis = (
    df.groupby("Category")
    .agg(
        Total_Sales=("Net_Sales", "sum"),
        Average_Sales=("Net_Sales", "mean"),
        Total_Quantity=("Quantity", "sum"),
        Total_Orders=("Order_ID", "count")
    )
    .sort_values(
        "Total_Sales",
        ascending=False
    )
)

category_analysis

              Total_Sales  Average_Sales  Total_Quantity  Total_Orders
Category
Electronics  3.280012e+08  133063.380710            7463          2465
Accessories  2.704215e+08  139680.526937            5946          1936
Wearables    8.047599e+07  134350.565192            1756           599

In [89]:
#11. City Analysis
city_sales = (
    df.groupby("City")["Net_Sales"]
    .sum()
    .sort_values(ascending=False)
)

city_sales

City
Mumbai       95319420.25
Delhi        92749536.20
Kolkata      89097190.75
Pune         86158164.50
Chennai      81493598.15
Hyderabad    78970882.70
Bangalore    78872613.90
Patna        76237315.70
Name: Net_Sales, dtype: float64

In [90]:
#Top city:
top_city = city_sales.idxmax()

print("Top City:", top_city)

Top City: Mumbai

In [91]:
#12. Customer Analysis
customer_sales = (
    df.groupby("Customer_ID")["Net_Sales"]
    .sum()
    .sort_values(ascending=False)
)

customer_sales.head(10)

Customer_ID
1699    2198853.00
1355    2087107.65
1618    2081240.60
1988    2038351.45
1247    1989933.55
1273    1974173.95
1187    1912250.60
1471    1884363.20
1925    1842285.00
1375    1839227.95
Name: Net_Sales, dtype: float64

In [92]:
#Customer Order Count
customer_orders = (
    df.groupby("Customer_ID")["Order_ID"]
    .count()
    .sort_values(ascending=False)
)

customer_orders.head(10)

Customer_ID
1726    15
1925    14
1439    13
1720    13
1247    12
1073    12
1355    12
1471    12
1528    12
1849    11
Name: Order_ID, dtype: int64

In [93]:
#13. Payment Method Analysis
payment_analysis = (
    df.groupby("Payment_Method")
    .agg(
        Total_Sales=("Net_Sales", "sum"),
        Orders=("Order_ID", "count"),
        Average_Order=("Net_Sales", "mean")
    )
    .sort_values(
        "Total_Sales",
        ascending=False
    )
)

payment_analysis

                 Total_Sales  Orders  Average_Order
Payment_Method
Net Banking     1.554859e+08    1092  142386.376694
Cash            1.343116e+08    1031  130273.100242
Debit Card      1.318790e+08     964  136803.912915
UPI             1.304764e+08     969  134650.554283
Credit Card     1.267459e+08     944  134264.696292

In [94]:
#14. Order Status Analysis
status_analysis = (
    df.groupby("Order_Status")["Order_ID"]
    .count()
)

status_analysis

Order_Status
Cancelled     876
Delivered    3312
Returned      812
Name: Order_ID, dtype: int64

In [95]:
#Cancellation rate
cancelled = np.sum(
    df["Order_Status"] == "Cancelled"
)

total_orders = len(df)

cancellation_rate = (
    cancelled / total_orders
) * 100

print(
    "Cancellation Rate:",
    round(cancellation_rate, 2),
    "%"
)

Cancellation Rate: 17.52 %

In [96]:
#Return rate:
returned = np.sum(
    df["Order_Status"] == "Returned"
)

return_rate = (
    returned / total_orders
) * 100

print(
    "Return Rate:",
    round(return_rate, 2),
    "%"
)

Return Rate: 16.24 %

In [97]:
#15. Rating Analysis
rating_analysis = (
    df.groupby("Rating")["Order_ID"]
    .count()
)

rating_analysis

Rating
1    1000
2    1004
3     988
4     986
5    1022
Name: Order_ID, dtype: int64

In [98]:
#Average rating:
average_rating = df["Rating"].mean()

print(
    "Average Rating:",
    round(average_rating, 2)
)

Average Rating: 3.01

In [102]:
#16. Sales Above Average
average_sales = df["Net_Sales"].mean()

high_value_orders = df[
    df["Net_Sales"] > average_sales
]

high_value_orders.head()

,Order_ID,Customer_ID,Product,Category,City,Quantity,Price,Discount,Payment_Method,Order_Status,Rating,Order_Date,Gross_Sales,Discount_Amount,Net_Sales,Month,Month_Number
1,10002,1687,Headphones,Accessories,Kolkata,3,93338,5,Cash,Delivered,3,2025-01-19,280014,14000.70,266013.30,January,1
2,10003,1751,Keyboard,Accessories,Chennai,3,76626,0,Debit Card,Delivered,4,2025-01-16,229878,0.00,229878.00,January,1
7,10008,1048,Keyboard,Accessories,Patna,5,76567,5,Debit Card,Delivered,2,2025-06-15,382835,19141.75,363693.25,June,6
8,10009,1511,Monitor,Electronics,Chennai,5,28238,0,Net Banking,Delivered,2,2025-02-28,141190,0.00,141190.00,February,2
11,10012,1116,Monitor,Electronics,Chennai,3,48424,0,Cash,Returned,4,2025-10-04,145272,0.00,145272.00,October,10

In [103]:
#17. NumPy where()
df["Sales_Level"] = np.where(
    df["Net_Sales"] >= average_sales,
    "High",
    "Low"
)

df[
    ["Order_ID", "Net_Sales", "Sales_Level"]
].head()

   Order_ID  Net_Sales Sales_Level
0     10001   112696.4         Low
1     10002   266013.3        High
2     10003   229878.0        High
3     10004    73674.0         Low
4     10005   117570.3         Low

In [104]:
#18. Outlier Analysis
Q1 = np.percentile(
    df["Net_Sales"], 25
)

Q3 = np.percentile(
    df["Net_Sales"], 75
)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Lower Limit: -177700.76875
Upper Limit: 427777.98125

In [105]:
#Find outliers:
outliers = df[
    (df["Net_Sales"] < lower_limit) |
    (df["Net_Sales"] > upper_limit)
]

print("Number of Outliers:", len(outliers))

Number of Outliers: 62

In [106]:
#19. Correlation Analysis
numeric_columns = [
    "Quantity",
    "Price",
    "Discount",
    "Rating",
    "Gross_Sales",
    "Discount_Amount",
    "Net_Sales"
]

correlation = df[
    numeric_columns
].corr()

correlation

,Quantity,Price,Discount,Rating,Gross_Sales,Discount_Amount,Net_Sales
Quantity,1.000000,-0.023368,0.015735,-0.002868,0.575185,0.384786,0.569109
Price,-0.023368,1.000000,-0.000722,0.001327,0.727589,0.470624,0.722595
Discount,0.015735,-0.000722,1.000000,0.021043,0.006680,0.600463,-0.092940
Rating,-0.002868,0.001327,0.021043,1.000000,0.009748,0.018097,0.007711
Gross_Sales,0.575185,0.727589,0.006680,0.009748,1.000000,0.653747,0.991980
Discount_Amount,0.384786,0.470624,0.600463,0.018097,0.653747,1.000000,0.552860
Net_Sales,0.569109,0.722595,-0.092940,0.007711,0.991980,0.552860,1.000000